# -*- coding: utf-8 -*-
"""MapLuxuryBudget.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xiv-MS2Dcnj4xtmCPAQLb-sxn9MYen1Y
"""

!pip install folium

import pandas as pd
import folium
from IPython.display import IFrame
from google.colab import files


data = [

    ("76051", "Budget", 32.8822, -97.1036),
    ("75034", "Budget", 33.1270, -96.8377),
    ("29607", "Budget", 34.8256, -82.3403),
    ("85260", "Budget", 33.5917, -111.8856),
    ("89146", "Budget", 36.1403, -115.2224),
    ("76017", "Budget", 32.6820, -97.1731),
    ("85284", "Budget", 33.3402, -111.9437),
    ("75062", "Budget", 32.8446, -96.9849),
    ("43228", "Budget", 39.9515, -83.1441),
    ("55110", "Budget", 45.0801, -93.0046),
    ("29406", "Budget", 32.9461, -80.0220),
    ("75228", "Budget", 32.8145, -96.6830),
    ("76180", "Budget", 32.8571, -97.2187),
    ("32225", "Budget", 30.3374, -81.5162),
    ("30096", "Budget", 33.9885, -84.1526),
    ("84115", "Budget", 40.7347, -111.9023),
    ("85297", "Budget", 33.2765, -111.7132),
    ("63123", "Budget", 38.5614, -90.3148),
    ("85382", "Budget", 33.6376, -112.2485),
    ("75234", "Budget", 32.9225, -96.8892),
    ("85014", "Budget", 33.5092, -112.0565),
    ("43017", "Budget", 40.1073, -83.1271),
    ("03103", "Budget", 42.9670, -71.4483),
    ("33619", "Budget", 27.9428, -82.3802),
    ("02062", "Budget", 42.1855, -71.1995),


    ("75093", "Luxury", 33.0356, -96.8044),
    ("30096", "Luxury", 33.9885, -84.1526),
    ("60540", "Luxury", 41.7484, -88.1620),
    ("76051", "Luxury", 32.8822, -97.1036),
    ("75209", "Luxury", 32.8504, -96.8264),
    ("60559", "Luxury", 41.7937, -87.9601),
    ("78209", "Luxury", 29.4862, -98.4465),
    ("33181", "Luxury", 25.8996, -80.1628),
    ("30076", "Luxury", 34.0329, -84.3183),
    ("20852", "Luxury", 39.0535, -77.1225),
    ("95129", "Luxury", 37.3084, -121.9951),
    ("22182", "Luxury", 38.9225, -77.2552),
    ("33614", "Luxury", 28.0060, -82.5069),
    ("98005", "Luxury", 47.6159, -122.1625),
    ("07631", "Luxury", 40.8933, -73.9722),
    ("77090", "Luxury", 30.0115, -95.4516),
    ("75024", "Luxury", 33.0805, -96.8042),
    ("94538", "Luxury", 37.5267, -121.9675),
    ("90621", "Luxury", 33.8753, -117.9934),
    ("77079", "Luxury", 29.7845, -95.6118),
    ("10019", "Luxury", 40.7656, -73.9858),
    ("30341", "Luxury", 33.8927, -84.2874),
    ("20904", "Luxury", 39.0672, -76.9787),
    ("33027", "Luxury", 25.9775, -80.3470),
    ("84115", "Luxury", 40.7347, -111.9023)
]


zip_df = pd.DataFrame(data, columns=["Zipcode", "Category", "lat", "lon"])


center_lat = zip_df['lat'].mean()
center_lon = zip_df['lon'].mean()
zip_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)


for _, row in zip_df.iterrows():
    color = 'blue' if row['Category'] == 'Luxury' else 'red'
    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=6,
        color=color,
        fill=True,
        fill_opacity=0.8,
        popup=f"Zipcode: {row['Zipcode']} ({row['Category']})"
    ).add_to(zip_map)


zip_map.save("LuxuryBudget_ZipMap.html")
IFrame('LuxuryBudget_ZipMap.html', width=900, height=500)
files.download("LuxuryBudget_ZipMap.html")